### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by veziak**

### CODE REVIEW

**Comment by veziak** [comment]
terraform plan

**Comment by veziak** [comment]
digger plan

**Comment by veziak** [comment]
digger unlock

**Comment by veziak** [comment]
digger plan

**Comment by motatoes** [comment]
digger plan

**Comment by motatoes** [comment]
digger apply

**Comment by motatoes** [comment]
digger plan

**Comment by veziak** [comment]
digger plan

**Comment by veziak** [comment]
digger plan

**Comment by veziak** [comment]
digger plan

**Comment by veziak** [comment]
digger plan

**Comment by veziak** [comment]
digger plan

**Comment by veziak** [comment]
digger plan

**Pull request closed without merging**
